### ISSUE TITLE
Loan Offer Acceptance UI - Transfer Collateral Step

### ISSUE THREAD

**Issue by livingrock7** [upscaletech/blocklendr.ui#13]

**Comment by Devilla** [comment]
Can you explain it a bit as per UI perspective?

**Comment by livingrock7** [comment]
Yes it will just prompt to transfer collateral after steps 12 and 11 has been done. 

basically,
list all loan offers with button 'take this loan'

next prompt where borrower picks collateral and terms (one of the objects from array) by clicking submit and then clicks accept (submit just locks the data and accept calls contract function as mentioned)

next prompt would be transfer collateral

**Comment by Devilla** [comment]
Done.
