### ISSUE TITLE
Creating Loan Offer - UI - multiple collaterals display 

### ISSUE THREAD

**Issue by livingrock7** [upscaletech/blocklendr.ui#8]
@Devilla check the issue with push currently it is failing when you add multiple objects in UI.

Give fields for MPR and LTV per collateral. collateral symbol will be added by user and corresponding values

Gather inputs and convert this array of objects to json string : acceptedCollateralMatadata

**Comment by Devilla** [comment]
![image](https://user-images.githubusercontent.com/15603274/64875830-77b97b80-d66b-11e9-862d-7f477417482b.png)
```Give fields for MPR and LTV per collateral. collateral symbol will be added by user and corresponding values``` in the right hand box alonside 

Loan amount 100 ETH

Collateral (not set)

Duration (not set) days  ?

**Comment by livingrock7** [comment]
Is this a question?

so how this will work like is:

Add your collateral +> Add your choice of accepted collaterals

Also give text fields for LTV and interest 

Once clicked next you can display collateral symbols in overview.

Duration works as usual in next tab

**Comment by livingrock7** [comment]
display apart, you need to store these array of objects and convert into json string
store in a variable called accepted collaterals

this variable will be passed into create loan offer.js

**Comment by Devilla** [comment]
Okay

**Comment by Devilla** [comment]
Done
